// Picked from https://chainlist.org/
export const DEFAULT_PUBLIC_RPC_LIST: Map<number, [string | undefined, string]> = new Map([
  [1, ['mainnet', 'https://ethereum-rpc.publicnode.com']],
  [11155111, ['sepolia', 'https://ethereum-sepolia-rpc.publicnode.com']],
  [137, ['polygon', 'https://polygon-bor-rpc.publicnode.com']],
  [80002, [undefined, 'https://rpc-amoy.polygon.technology']],
  [1101, ['polygon-zkevm', 'https://zkevm-rpc.com']],
  [56, ['bnb', 'https://bsc-rpc.publicnode.com']],
  [97, ['bnb-testnet', 'https://bsc-testnet-rpc.publicnode.com']],
  [10, ['optimism', 'https://optimism-rpc.publicnode.com']],
  [11155420, ['optimism-sepolia', 'https://sepolia.optimism.io']],
  [42161, ['arbitrum', 'https://arb1.arbitrum.io/rpc']],
  [421614, ['arbitrum-sepolia', 'https://sepolia-rollup.arbitrum.io/rpc']],
  [42170, ['arbitrum-nova', 'https://arbitrum-nova.publicnode.com']],
  [43114, ['avalanche', 'https://avalanche-c-chain-rpc.publicnode.com']],
  [43113, ['avalanche-testnet', 'https://avalanche-fuji-c-chain-rpc.publicnode.com']],
  [100, ['gnosis', 'https://gnosis-pokt.nodies.app']],
  [8453, ['base', 'https://mainnet.base.org']],
  [84532, ['base-sepolia', 'https://base-sepolia-rpc.publicnode.com']],
  [19011, ['homeverse', 'https://rpc.mainnet.oasys.homeverse.games']],
  [40875, ['homeverse-testnet', 'https://rpc.testnet.oasys.homeverse.games']],
  [660279, [undefined, 'https://xai-chain.net/rpc']],
  [37714555429, [undefined, 'https://testnet-v2.xai-chain.net/rpc']],
  [3776, ['astar-zkevm', 'https://rpc.startale.com/astar-zkevm']],
  [6038361, ['astar-zkyoto', 'https://rpc.startale.com/zkyoto']],
  [2730, [undefined, 'https://xr-sepolia-testnet.rpc.caldera.xyz/http']],
  [40, [undefined, 'https://mainnet-asia.telos.net/evm']],
  [1946, [undefined, 'https://rpc.minato.soneium.org']],
  [7668, [undefined, 'https://root.rootnet.live/archive']],
  [8333, [undefined, 'https://mainnet-rpc.b3.fun']],
  [13371, [undefined, 'https://rpc.immutable.com']],
  [33139, [undefined, 'https://rpc.apechain.com']],
  [81457, [undefined, 'https://blast-rpc.publicnode.com']],
  [33111, [undefined, 'https://rpc.curtis.apechain.com']],
  [1482601649, [undefined, 'https://mainnet.skalenodes.com/v1/green-giddy-denebola']],
  [37084624, [undefined, 'https://testnet.skalenodes.com/v1/lanky-ill-funny-testnet']],
  [13473, [undefined, 'https://rpc.immutable.com']],
  [7672, [undefined, 'https://porcini.rootnet.app/archive']]
])

// These are hardhat test networks
export const IGNORED_CHAIN_IDS = new Set([31337, 31338])
